// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Alert(arg1) {
  return window['go']['main']['App']['Alert'](arg1);
}

export function Call(arg1, arg2, arg3) {
  return window['go']['main']['App']['Call'](arg1, arg2, arg3);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function Process() {
  return window['go']['main']['App']['Process']();
}
