// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {internal} from '../models';

export function Alert(arg1:string):Promise<void>;

export function Call(arg1:string,arg2:internal.Params,arg3:internal.Config):Promise<internal.Result>;

export function GetConfig():Promise<Record<string, any>>;

export function OpenFileDialog():Promise<string>;

export function Process():Promise<Array<Record<string, any>>>;
